window.clutter = {
	name: 'Clutter',
	items: [
		'Abacus',
		'Amulet',
		'Arrows',
		'Azurite',
		'Backpack',
		'Ball Bearings (bag of 1,000)',
		'Bedroll',
		'Bell',
		'Birdpipes',
		'Bit and Bridle',
		'Block and Tackle',
		'Blue quartz',
		'Bottle, Glass',
		'Brewer\'s Supplies',
		'Calligrapher\'s Supplies',
		'Carpenter\'s Tools',
		'Cartographer\'s Tools',
		'Chain (10 feet)',
		'Clothes, Costume',
		'Clothes, Fine',
		'Clothes, Traveler\'s',
		'Clothing, cold weather',
		'Cobbler\'s Tools',
		'Cook\'s Utensils',
		'Crossbow Bolts',
		'Crowbar',
		'Crystal',
		'Dagger',
		'Dragonchess Set',
		'Drum',
		'Emblem',
		'Eye agate',
		'Fishing Tackle',
		'Flute',
		'Forgery Kit',
		'Hand Drum',
		'Healer\'s Kit',
		'Herbalism Kit',
		'Horn',
		'Ink (1 ounce bottle)',
		'Insect Repellent-Salve',
		'Lantern, Bullseye',
		'Lantern, Hooded',
		'Lapis Lazuli',
		'Leather',
		'Leatherworker\'s Tools',
		'Lock',
		'Malachite',
		'Manacles',
		'Mason\'s Tools',
		'Mirror, Steel',
		'Moss agate',
		'Net',
		'Obsidian',
		'Orb',
		'Padded',
		'Painter\'s Supplies',
		'Pan Flute',
		'Perfume (vial)',
		'Pick, Miner\'s',
		'Pot, Iron',
		'Potter\'s Tools',
		'Quiver',
		'Rain Catcher',
		'Reliquary',
		'Robes',
		'Rod',
		'Rope, Hempen (50 feet)',
		'Rope, Silk (50 feet)',
		'Saddlebags',
		'Scale, Merchant\'s',
		'Shawm',
		'Shovel',
		'Sickle',
		'Signet Ring',
		'Smith\'s Tools',
		'Snowshoes',
		'Songhorn',
		'Spikes, Iron (10)',
		'Sprig of Mistletoe',
		'Three-Dragon Ante Set',
		'Totem',
		'Turquoise',
		'Vial',
		'Weaver\'s Tools',
		'Whip',
		'Woodcarver\'s Tools',
		'Apron',
		'Belt',
		'Boots,high,hard',
		'Boots,high,soft',
		'Boots,low,hard',
		'Boots,low,soft',
		'Cap',
		'Cape,cloth',
		'Cape,fur',
		'Cloak,cloth',
		'Cloak,fur',
		'Cloth,canvas',
		'Cloth,cotton',
		'Cloth,linen',
		'Cloth,satin',
		'Cloth,silk',
		'Cloth,velvet',
		'Cloth,wool',
		'Dress',
		'Fur trimming',
		'Girdle,broad',
		'Girdle,normal',
		'Gloves,cloth',
		'Gloves,leather',
		'Gown,common',
		'Hat,cloth',
		'Hat,fur',
		'Hat,straw',
		'Jerkin',
		'Loinclot',
		'Needle,sewing',
		'Robe',
		'Sandals',
		'Scissors',
		'Shirt/blouse',
		'Thread,1 spool',
		'Trouser/skirt',
		'Vest,cloth',
		'Vest,furBelladona,sprig',
		'Garlic,bud',
		'Wolvesbane,sprig',
		'Air bladder',
		'Backpack,leather',
		'Bag,leather',
		'Bedroll',
		'Bell',
		'Bird cage',
		'Blanket',
		'Book,blank,100 pages',
		'Book,parchment',
		'Book,vellum',
		'Bottle or flask',
		'Box,iron,small',
		'Bucket',
		'Candle,tallow',
		'Candle,wax',
		'Candle snuffer',
		'Cane,walking',
		'Chain,iron,1\',fine,small',
		'Chain,iron,1\',heavy',
		'Chain,iron,1\',light',
		'Chain,iron,1\',medium',
		'Chalk,powder',
		'Chalk,stick of',
		'Charcoal,10 lb. bag of',
		'Chest,wooden,small',
		'Chisel',
		'Coal, 10 lb. bag of',
		'Cologne/perfume,1 oz',
		'Comb',
		'Cord,10\'',
		'Crowbar',
		'Dice set',
		'Dice set (loaded)',
		'Drill,iron',
		'Earspoon',
		'Fishhook',
		'Fishing net',
		'Flint and steel',
		'Glass',
		'Glass bottle',
		'Glue,2 oz. pot of',
		'Hacksaw',
		'Hairbrush',
		'Hammock',
		'Hourglass',
		'Ink,2 oz. pot of',
		'Jar,glass',
		'Jug,clay',
		'Lamp,oil',
		'Lantern,beacon',
		'Lantern,bullseye',
		'Lantern,hooded',
		'Lantern,waterproof',
		'Lard,pint of',
		'Magnifying glass',
		'Manacles,pair of,& key',
		'Map of the known world',
		'Merchant\'s scale',
		'Metal file',
		'Mirror,large,metal',
		'Mirror,small,silver',
		'Nails,iron,100',
		'Oar',
		'Oil,flask of',
		'Paddle',
		'Padlock & key',
		'Pail',
		'Paint,1 gallon of',
		'Paint brush,fine',
		'Paint brush,large',
		'Paint brush,medium',
		'Papyrus,1 sheet',
		'Parchment,1 sheet',
		'Pen,fine,wooden',
		'Pen,quill',
		'Pick axe,mining',
		'Pick,tooth,5 score of',
		'Pen,fine,metal',
		'Pipe,smoking',
		'Pipeweed/tobacco',
		'Pliers',
		'Pot,iron cooking',
		'Pouch,belt,large',
		'Pouch,belt,small',
		'Pulley',
		'Purse',
		'Quilt',
		'Razor',
		'Rope,50\' hemp',
		'Rope,50\' superior',
		'Rope,50\' silk',
		'Sack,large',
		'Sack,small',
		'Saw,one man',
		'Skin,water/wine',
		'Soap,8 oz. bar of',
		'Spade/shovel',
		'Spike,iron,large',
		'Spyglass',
		'String,50\'',
		'Thieves\' picks & tools',
		'Tinder Box with flint & steel',
		'Torch,normal',
		'Torch,small',
		'Vial,ceramic',
		'Vial,crystal',
		'Vial,metal',
		'Wallet',
		'Waterclock',
		'Wax,candle,lb',
		'Wax,sealing,lb',
		'Whetstone',
		'Whistle',
		'Wig',
		'A little bag of troll poop',
		'A ball of yarn',
		'Two mismatched socks',
		'A single shoelace'
	]
};