window.clutter = {
	name: 'Clutter',
	items: [
		'Abacus',
		'Amulet',
		'Arrows',
		'Azurite',
		'Backpack',
		'Ball Bearings (bag of 1,000)',
		'Bedroll',
		'Bell',
		'Birdpipes',
		'Bit and Bridle',
		'Block and Tackle',
		'Blue quartz',
		'Glass Bottle',
		'Brewer\'s Supplies',
		'Calligrapher\'s Supplies',
		'Carpenter\'s Tools',
		'Cartographer\'s Tools',
		'Chain (10 feet)',
		'Costume',
		'Fine Clothes',
		'Traveler\'s Clothes',
		'cold weather Clothing',
		'Cobbler\'s Tools',
		'Cook\'s Utensils',,
		'Crowbar',
		'Crystal',
		'Dagger',
		'Drum',
		'Emblem',
		'Eye agate',
		'Fishing Tackle',
		'Flute',
		'Forgery Kit',
		'Hand Drum',
		'Healer\'s Kit',
		'Herbalism Kit',
		'Horn',
		'Ink (1 ounce bottle)',
		'Insect Repellent-Salve',
		'Decorative Lantern',
		'Hooded Lantern',
		'Lapis Lazuli',
		'Leather',
		'Leatherworker\'s Tools',
		'Lock',
		'Malachite',
		'Manacles',
		'Mason\'s Tools',
		'Mirror, Steel',
		'Moss agate',
		'Net',
		'Obsidian',
		'Orb',,
		'Painter\'s Supplies',
		'Pan Flute',
		'Perfume (vial)',
		'Miner\'s Pick',
		'Iron Pot',
		'Ceramic Pot',
		'Potter\'s Tools',
		'Quiver',
		'Rain Catcher',
		'Reliquary',
		'Robes',
		'Rod',
		'Hempen Rope (50 feet)',
		'Silk Rope (50 feet)',
		'Saddlebags',
		'Merchant\'s Scale',
		'Shawm',
		'Shovel',
		'Sickle',
		'Signet Ring',
		'Smith\'s Tools',
		'Snowshoes',
		'Songhorn',
		'Iron Spikes (10)',
		'Sprig of Mistletoe',
		'Totem',
		'Turquoise',
		'Vial',
		'Weaver\'s Tools',
		'Whip',
		'Woodcarver\'s Tools',
		'Apron',
		'Belt',
		'High hard boots',
		'High soft boots',
		'low hard boots',
		'low soft boots',
		'Cap',
		'Cloth Cape',
		'Fur Cape',
		'Cloth Cloak',
		'Fur Cloak',
		'Canvas Cloth',
		'cotton fabric',
		'linen fabric',
		'satin fabric',
		'silk fabric',
		'velvet fabric',
		'wool fabric',
		'A pretty dress',
		'Fur trimming',
		'Broad Girdle',
		'Girdle',
		'Cloth Gloves',
		'Leather Gloves',
		'Common gown',
		'Cloth hat',
		'Fur hat',
		'Straw hat',
		'Jerkin',
		'sewing needle',
		'Scissors',
		'Thread,1 spool',
		'Vest,furBelladona,sprig',
		'Garlic,bud',
		'Wolvesbane,sprig',
		'Air bladder',
		'Backpack,leather',
		'Bag,leather',
		'Bedroll',
		'Bell',
		'Bird cage',
		'Blanket',
		'Book,blank,100 pages',
		'Book,parchment',
		'Book,vellum',
		'Bottle or flask',
		'Box,iron,small',
		'Bucket',
		'Candle,tallow',
		'Candle,wax',
		'Candle snuffer',
		'Walking cane',
		'Chain,iron,1\',fine,small',
		'Chain,iron,1\',heavy',
		'Chain,iron,1\',light',
		'Chain,iron,1\',medium',
		'Chalk,powder',
		'Chalk,stick of',
		'Charcoal,10 lb. bag of',
		'Chest,wooden,small',
		'Chisel',
		'Coal, 10 lb. bag of',
		'Cologne/perfume,1 oz',
		'Comb',
		'Cord,10\'',
		'Crowbar',
		'Dice set',
		'Dice set (loaded)',
		'Drill,iron',
		'Earspoon',
		'Fishhook',
		'Fishing net',
		'Flint and steel',
		'Glass',
		'Glass bottle',
		'Glue,2 oz. pot of',
		'Hacksaw',
		'Hairbrush',
		'Hammock',
		'Hourglass',
		'Ink,2 oz. pot of',
		'Jar,glass',
		'Jug,clay',
		'Lamp,oil',
		'Lantern,beacon',
		'Lantern,bullseye',
		'Lantern,hooded',
		'Lantern,waterproof',
		'Lard,pint of',
		'Magnifying glass',
		'Manacles,pair of,& key',
		'Map of the known world',
		'Merchant\'s scale',
		'Metal file',
		'Mirror,large,metal',
		'Mirror,small,silver',
		'Nails,iron,100',
		'Oar',
		'Oil,flask of',
		'Paddle',
		'Padlock & key',
		'Pail',
		'Paint,1 gallon of',
		'Paint brush,fine',
		'Paint brush,large',
		'Paint brush,medium',
		'Papyrus,1 sheet',
		'Parchment,1 sheet',
		'Pen,fine,wooden',
		'Pen,quill',
		'Pick axe,mining',
		'Pick,tooth,5 score of',
		'Pen,fine,metal',
		'Pipe,smoking',
		'Pipeweed/tobacco',
		'Pliers',
		'Pot,iron cooking',
		'Pouch,belt,large',
		'Pouch,belt,small',
		'Pulley',
		'Purse',
		'Quilt',
		'Razor',
		'Rope,50\' hemp',
		'Rope,50\' superior',
		'Rope,50\' silk',
		'Sack,large',
		'Sack,small',
		'Saw,one man',
		'Skin,water/wine',
		'Soap,8 oz. bar of',
		'Spade/shovel',
		'Spike,iron,large',
		'Spyglass',
		'String,50\'',
		'Thieves\' picks & tools',
		'Tinder Box with flint & steel',
		'Torch,normal',
		'Torch,small',
		'Vial,ceramic',
		'Vial,crystal',
		'Vial,metal',
		'Wallet',
		'Waterclock',
		'Wax,candle,lb',
		'Wax,sealing,lb',
		'Whetstone',
		'Whistle',
		'Wig',
		'A little bag of troll poop',
		'A ball of yarn',
		'Two mismatched socks',
		'A single shoelace'
	]
};