window.gutWrench = {
	name: 'Gut Wrenching Loot',
	items: [
		'A picture of the family',
		'A letter from a temple thanking them for their donation to the orphans',
		'Some crumpled bits of paper, multiple drafts of a birthday card for their partner',
		'A hand drawn picture signed by a child',
		'A tattered love letter dated years ago',
		'A love poem ripped out of a book with a handwritten "Found this for you" in a heart',
		'A list saying, "Remember: eggs, flour, spatula, do it for them"',
		'They have a tattoo of a dog that says RIP below and years of life suggesting it was their childhood pet',
		'A photobooth style short reel of pictures with them and some buddies being silly',
		'A letter from the humane society thanking them for their donation',
		'Bagged lunch with a heart drawn on the bag',
		'A child\'s toy and a note in childish writing "so u arnt lonly" with it',
		'A keychain with two initials in a heart with a date (presumably wedding) 1d6 years back',
		'A copper coin that\'s been through one of those presses that they have at tourist places, for a child theme-park',
		'A recent child\'s grade report showing quite good grades',
		'A note from their parents saying both are sick but don\'t worry they\'ll be fine, and some overtime pay slips',
		'A schedule for a recreational sports league and a list of names, some crossed off, suggesting they were putting the team together',
		'Pocket is full of dog treats and poo pickup bags, clearly forgotten there after a morning walk',
		'A few drafts of a (still) poorly rhymed love poem to a partner',
		'A small rolled-up painting of a family, including a younger-looking version of the person you found this on',
		'"Happy Early Retirement" card from their buddies with the date in two weeks.',
		'A map showing the last known location of their long lost parent (and a bunch of other locations/clues crossed off a long list that started hundreds of miles away).',
		'A tattoo saying "as long as you have breath, there is hope".',
		'A ransom note from a kidnapper who has their family held hostage with a looming deadline and a crazy task to accomplish.',
		'A tiny, hinged velvet box containing a silver ring with a single gem embedded in it.',
		'A note from a wife congratulating on a promotion for a dock worker and reminder to pick up a loaf of bread on the way home once',
		'A clay piece with a drawing of a woman and baby in a soldier\'s pocket far from home.',
		'A letter with the following written inside "we only need 300 more gold until we can bring her back and live peacefully once again as a family"',
		'A worn letter in childish scrawl asking when they will be coming home',
		'A brand new copy of "Volo\'s Guide to What to Expect When You\'re Expecting" with a couple of pages dog-eared  in and "Congratulations!" written on the inside cover',
		'A pair of carefully wrapped baby shoes, never worn',
		'A note detailing back home talking about how they almost had enough money to buy their father\'s house back from the debt collector',
		'A bill from a sorcerer listing an exorbitant amount of gold for a spell to cure a terminally ill child.',
		'A burial urn and slightly tear stained map of the local region with an "X" marking a nearby location.',
		'A pouch of small medicinal vials labelled with different names, with a handwritten note detailing dosages and urgency in delivery.',
		'An invitation to a charity ball rewarded for substantial devotion and contribution to community and individual wellbeing.',
		'A small wooden trinket and a list clear written by a child with the heading "birhday ideaz"',
		'A key with a tag that says it belongs to a palace/tavern/jail/brothel',
		'3 tickets for passage on a ship and a letter from a human trafficker',
		'A scroll of revivify and a letter of truce/peace from a rival kingdom',
		'A small pet, like a salamander or a rat, that tries to wake up its deceased owner.',
		'A crude drawing of a knight with the words "to scar away th monsturs" written in crayon on it',
		'A tiny, hinged velvet box containing a silver ring with a single diamond embedded in it.',
		'A special looking key',
		'A gold ring worn on a necklace with the word "Forever" engraved on the inside',
		'poorly sewn mittens with a smiley face on them, looks like a young child might of made them',
		'A fancy thank you letter saying "Still cannot believe you taught him to read, all of the years or you reading to him while we were gone paid off."',
		'A silver locket that when opened you see a drawing of him , what seems to be his wife and 2 children. On the locket face it says, You are my rock!',
		'A note listing demands to trade for a fertility potion.',
		'A key wrapped in parchment. On the parchment it says "happy one year anniversary. I finally bought us a farm to get us out of that city."',
		'Bottle of troll blood mixed with a Nothic Tear. Note: "Darling! I have finally got it! The sage said this will cure our son\'s blindness! I am so excited to get our lives back on track."',
		'Last page of journal: I am so glad my contract will be finished tomorrow. I just want to come home to the farm. Cannot wait to meet our newborn for the first time!',
		'Letter from father "I know you wanted to adventure and be like the books you have read. But your mother passed away last night after a high fever. Please come home, you are all I have.',
	]
}