window.actions = {
	name: 'Actions',
	items: [
		'Sweeping the floor',
		'Eating',
		'Playing cards',
		'Knitting',
		'Sketching',
		'Drinking',
		'Asleep',
		'Jacking off',
		'Pooping',
		'Relaxing',
		'Looking about',
		'Patching clothes',
		'Cooking',
		'Talking to themselves',
		'Dancing',
		'Humming to themselves',
		'Crying',
		'Tending to a plant',
		'Painting',
		'Practising a language',
		'Sitting by a fire',
		'Staring into the distance',
		'Smoking',
	]
};