window.npcFlavor = {
	name: 'Flavor',
	items: [
		'Smells of pickles',
		'Pimple on nose',
		'Acne',
		'Bright yellow scarf',
		'Missing all but one tooth',
		'Missing front teeth',
		'Terribly bad breath',
		'Very clean',
		'Tattooed',
		'Muscular',
		'Thin',
		'Tall',
		'Short',
		'Fidgets',
		'Smokes a pipe',
		'Loves reading',
		'Missing finger',
		'Extravagent clothing',
		'Falls asleep easily',
		'Lots of jewelery',
		'Covered in dirt',
		'Always sketching',
		'Gambling addict',
		'Attractive',
		'Ugly',
		'Smells of fresh cut grass',
		'Always itchy',
		'Nervous - always looking over shoulder',
		'Jogs in place while talking',
		'Always snacking, talks with their mouth open',
		'Carries a notebook and writes everything down - whether it seems important or not',
		'talks to themselves',
		'Announces his/her emotions before speaking, but speaks monotonously. "Enthusiastic. I love the color of your sweater."',
		'Puffing a cigar, but coughing as if s/he doesn\'t smoke often.',
		'Carries a small pet around and speaks for it.',
		'Terrified of magic. Distances themselves from spellcasters and flinches at anything from fireball to prestidigitation.',
		'Uses air quotes wrong, meaning to add "emphasis" instead (for instance, I\'m so "pleased" to see you; There\'s a great "reward" in it for you; You\'re a "great" DM.)',
		'It\'s as though blinking doesn’t come naturally to them, always scrunching up their face to do so',
		'Often belches loudly and is overly apologetic for doing so',
		'Is constantly slicking back their hair nervously',
		'Always trying to feed people ("You look hungry.", "You\'re too skinny! Eat this!", etc.).',
		'Always impeccably dressed: hat, coat, and a co-ordinated handkerchief in a jacket pocket. They have a hanky for themselves in a back pocket.',
		'Has a "lazy" eye. Except it’s actually looking at the other party members or one of the doors.',
		'Is blind. But has crazy high perception so they just can’t read facial expressions.',
		'Very obviously picks wedgies and sniffs fingers afterwards',
		'Random pronounced eye twitch, which NPC will tell you he had ever since he won a fight with an owl bear',
		'Appears to be glaring angrily at whoever talks to them. Is not actually ever really angry.',
		'They are wearing a different, ridiculous hat whenever the PCs see them',
		'They do not speak common, but speak almost any other language.',
		'Looks so ordinary that you can\'t find a single distinctive thing about them. Perfectly average',
		'Ears stick out a lot',
		'Has buck teeth',
		'Has an unnusually pointy nose',
		'Has an unnusually flat nose',
		'Has long, stright hair',
		'Has long, wavy hair',
		'Has long, curly hair',
		'Hair is in matted dreadlocks - which smell foul',
		'Has short hair',
		'Has a distinctive monobrow',
		'Is blind in one eye',
		'Has a scar over their left eye',
		'The tip of their nose has been cut off'
	]
}