window.npcSecrets = {
	name: 'Secret',
	items: [
		'Grows flowers',
		'Was going to leave next week',
		'Has never actually killed anyone',
		'Gives half his pay to charity',
		'Just got a haircut',
		'Has social anxiety',
		'Nearly has enough saved for new boots',
		'Doesn\'t believe their own race exists',
		'Is a hoarder. Their house is full of junk',
		'Doesn\'t understand sarcasm.',
		'Eats boogers - not just his own',
		'NPC is an EXTREME germaphobe. Avoids shaking hands, is sneezed on (or anything worse) he/she straight up passes out',
		'This character killed and replaced the person they purport to be. Their story isn\'t completely straight and they urge their friends and family to self-sabotage',
		'Klepto: This character will try to steal from people whenever they can. Give them proficiency in sleight of hand.',
		'This character is either wanted, or exiled from a foreign nation for treason. They go by a fake name and will go to any length to avoid being found out.',
		'This character has adopted a young orphan who they are highly protective of.',
		'This characters alignment is evil, but they do their best to hide it from others by framing their self interest and sadism as something wholesome or as being motivated for the greater good.',
		'Was once an adventurer',
		'Dreams of owning a bakery',
		'Made his own uniform/clothes/armour',
		'Is a polyglot - speaks a LOT of languages',
		'Is afraid of the dark',
		'Is very androdgenous but hates being misgendered',
		'Has low self esteem and wants to be liked by everyone',
		'Cheats when gambling and is terrified someone will find out',
		'Murdered a local shopkeeper and stashed their body under the floorboards. Is afraid of being found out',
		'Hears voices - hides it somewhat well',
		'Has an existential fear of death',
		'Sexually repressed - can\'t handle any sexuality or even undergarments',
		'Afraid of spiders',
		'Racist towards anyone but their own race',
		'Racist towards their OWN race',
		'Afraid of closed spaces',
		'Afraid of open spaces',
		'Afraid of witches and witchcraft (doesn\'t mind wizards)',
		'Faints at the sight of blood',
		'Distrusts children - maybe they\'re goblins in disguise!',
		'Afraid of being forgotten and leaving no legacy',
		'Cannot swim',
		'Heartbroken, disenfrachised with love and afraid of being emotionally hurt (again)',
		'Is vegan',
		'Strictly alcohol free',
		'Has a pet mouse',
		'Is interested in learning magic, but cannot cast any',
		'Conspiracy theorist - the world is run by goblins!',
		'Doesn\' believe in the gods',
		'Has no interest in money or wealth of any kind',
		'Has a magical pet rock which gives adive, but only the NPC can hear it. Dubious whether it actually works',
		'Thinks people who bath are snobbish, dislikes anyone clean',
		'Dislikes anyone dirty',
		'Honest to a fault - will never lie',
		'Was once betrayed by their superior and now doesn\' trust people',
		'Is afraid of horses and any other form of transportation besides their own two legs',
		'Dislikes their own children and drinks to numb the pain',
		'I wanted to be a ballerina. This NPC dislikes whatever occupation it has now. He/She always wanted to be a dancer but never had the chance. He/She is actually pretty good at will dance during conversations with the party if possible.',
		'',
	]
}