window.voices = {
	name: 'Voices',
	items: [
		'Speaks slowly and tends to mumble. Tends to ramble.',
		'Speaks in quick bursts before pausing to think.',
		'Has a naturally low voice, and every paragraph is a sentence. His english teacher hated him.',
		'Nasally voice. Takes deep breaths every few sentences.',
		'Rarely speaks, but has little volume control.',
		'This person seems to purr their words more than a tabaxi. You don\'t think they\'re trying to be sexy but you do have the urge to rub their belly.',
		'This person is definitely trying to sound deep and tough for the Adventurers. This facade is betrayed by the few squawks and squeaks they cannot surpress.',
		'This old lady bubbles and tittles like a babbling brook. Her constant giggles sound like a stream passing over stones.',
		'Clicks their tongue as the struggle to think of the right word to say',
		'Deep bassy rumble, like that of a deep cave',
		'Sometime repeats a word in their sentences like a skaven',
		'Speaks without using Contractions (ie can\'t, won\'t, I\'m)',
		'speaks in a morbid, dark tone. Tends to enunciate words in order to enhance their dramatic appeal.',
		'Clears throat waaaayyyy too much',
		'Speaks without emotion, but announces what emotion he would be speaking with.',
		'Slow, deep and cold. Conjures images of the watery depths below an ice shelf. (Best coupled with a hard unblinking stare directly at the player they are speaking to)',
		'Speaks with heavy sarcasm',
		'A severe stutter making understanding what they are saying difficult and very drawn out.',
		'Speaks incredibly shakespearean when around others to appear fancier, but normally when alone.',
		'Speaks in soft, eloquent tones that are smooth as silk (succubus, rogue, con-artist)',
		'Speaks so fast, you can\'t make out any punctuations, will only stop if you interrupt them',
		'A mouth full of gravel. Gruff, raspy, and deep, the party sometimes has to ask them to repeat themselves several times before receiving a clear response.',
		'Always seems to be chewing something',
		'Speaks one word per reply',
		'Ends almost every bit of dialogue with "That reminds of the time when..." and rambles off until stopped',
		'Sucks their teeth and gives a heavy sigh before replying to anything',
		'Is constantly humming a tune, and fits the words of their speech to the song\'s melody. (For example: to the tune of Mary Had A Little Lamb, "Would you like to buy this sword? It\'s quite nice. What a slice! Goes for only twenty gold, then it\'s yourrrrssss")',
		'Ends every sentence in a preposition.',
		'Has a chipped tooth that makes their S\'s sounds whistle.',
		'Speaks slowly and sounds as if constantly about to yawn.',
		'Enunciates clearly and speaks melodiously, sometimes ominously.',
		'Their every sentence sounds like a joyous announcement.',
		'Speaks almost entirely without moving their jaw.',
		'Only speaks in questions.',
		'Speaks in grunts and few-worded sentences (my go-to for grumpy bartenders)',
		'Dramatic diva, high voice, lots of body language and flailing around. Add clinky jewellery (bracelets, necklaces, head ornaments) for even moar drama.',
		'Slight lisp, more pronounced in certain situations (stress, foreign language, fear).',
		'Is mock-offended very frequently; exaggerated gasps and a hand to his chest.',
		'Voice is very "bouncy", with strong pitch changes in each word or phrase. Exaggeration of typical variation.',
		'Uses old-fashioned interjections: Gee-golly! By my stars! Land’s sake! Zounds! Hark! Cripes!',
		'You can hear their smile in their words. Although they\'re a stranger to you, they speak to you with the easy familiarity of a friend.',
		'Constant quick-talker. It\'s like their mouth is struggling to keep up with their racing mind.',
		'Every sentence seethes with barely-contained outrage. They\'re not necessarily angry at you; they\'re angry at the whole world, and that anger comes across in their voice.',
		'Constantly cuts you off, because they\'re arrogant, rude, and a terrible listener. (This one will likely annoy your players, so use cautiously.)',
		'Speaks in a lazy drawl and enunciates in an exaggerated manner. It\'s like they think words are delicious, so they savor every one.',
		'Speaks in enigmatic short stories rather than proper sentences. "The owl must once again hunt down the rabbit" means "I\'m going out to get food."',
		'Light and airy, as though every word comes out like a sigh.',
		'Large gasps in the middle of sentences. Used by powerful beings that aren\'t used to breathing.',
		'Speaks in a mimicking tone to one of the player characters.',
		'Has a rumbling baritone voice that reminds you of metal bending.',
		'Doesn\'t use pauses at the end of sentences, meaning they speak fast but monotonous, with random stops in middle of them to catch a breath.',
		'Uses actions to describe things instead of adjectives (for Lizarddolk, they say "wind brings cold to me" instead of "wind makes me cold")',
		'Speaks fast with a small lisp',
		'Deep voice with rolling R\'s',
		'Pronounces most S\'s as Z\'s',
		'French accent',
		'High pitched and excited',
		'Often laughs before speaking',
		'Relaxed with a lot of content humming',
		'Spanish accent',
		'Scratchy and weak',
		'Posh accent',
		'Mostly speaks with clenched teeth',
		'Soft and melodious',
		'Pronounces most O\'s as U\'s',
		'Eastern European accent',
		'Old and thin voice',
		'Farmer\'s accent',
		'Puts emphasis on the wrong parts of words',
		'Sighs with exhaustion a lot',
		'Frivolous and kind',
		'Scottish accent',
		'Uses the word "Darling" a lot',
		'Loud with a lot of bravado',
		'Often pauses mid-sentence to think',
		'Pre-pubescent and boyish',
		'Notes of animalistic growling and snarling',
		'Smooth and feminine',
		'Raspy',
		'Italian accent',
		'Excited and jittery',
		'Warm and comforting',
		'Middle-Eastern accent',
		'Inhaling and exhaling with a thin wheeze',
		'Voice often breaking',
		'Half singing most sentences',
		'Speaks in the back of the mouth',
		'Scandinavian accent',
		'Speaks like royalty, uses complex vocabulary',
		'Words like "its" and "is" become "eats" and "ease"',
		'Vocalises with an open throat',
		'Skittish',
		'Jamaican accent',
		'Frightful',
		'Hard of hearing, loud',
		'American accent',
		'Smacks lips while talking',
		'Vocalises in the front of the mouth',
		'Tuts and clicks tongue a lot',
		'Adds syllables to words to emphasize',
		'Vocalises with a squeezed throat',
		'Squeaky',
		'Pirate accent',
		'Speaks like their tongue is numb',
		'Classic creaky witch voice',
		'Spits and stutters whilst talking',
		'Speaks with their lower jaw jutted out',
		'Irish accent',
		'Keeps vowels as short as possible',
		'Mid range voice',
		'Transatlantic accent',
		'Cold and demanding voice',
		'German accent',
		'Sensual and smooth',
		'Indian accent',
		'Nasal tone',
		'Often pronounces difficult words wrong',
		'Forgets to breath when speaking',
		'Hollow sounding voice',
		'Deaf - Uses sign language',
		'Slurs words',
		'Speaks like they have a cold/blocked nose',
		'Uses figure of speach often',
		'Often spits out words with contempt',
		'Uses the words "uh" and "uhm" a lot',
		'Enjoys rhyming sentences',
		'Sore throat, coughing a lot',
	]
};